### ISSUE TITLE
"stylegan2_arch.py" seems to be missing

### ISSUE THREAD

**Issue by styler00dollar** [TencentARC/GFPGAN#1]
GFPGANv1 seems to import "stylegan2_arch.py" [here](https://github.com/TencentARC/GFPGAN/blob/88fd720a48f2b9e9e2b094e79b51a8d420615167/archs/gfpganv1_arch.py#L7), but there is no such file in this repo. `StyleGAN2Generator` and several other things are missing. [This file](https://github.com/xinntao/BasicSR/blob/cf1e32cdfc9710041ed497e9f5c155ceb7567c8f/basicsr/archs/stylegan2_arch.py) from the BasicSR repo should be included in this repo as well.

**Comment by BounharAbdelaziz** [comment]
Indeed, I think there are many dependencies with the [BasicSR repository](https://github.com/xinntao/BasicSR)

**Comment by xinntao** [comment]
It depends on BasicSR for both training and inference. 

You can easily install basicsr by `BASICSR_EXT=True pip install basicsr`

A colab example: 

https://colab.research.google.com/drive/1sVsoBd9AjckIXThgtZhGrHRfFI6UUYOo
