### ISSUE TITLE
Final Quality

### ISSUE THREAD

**Issue by GOZARCK** [TencentARC/GFPGAN#10]
in whole image --paste_back option,
 the face restoration is 512x512, I would like the original image to be adjusted to the new size of the restored face and not the other way around, bc the image with the restored face when returning to the original image loses quality.
i was tried --upscale_factor but not work or is not implemented.
many thanks

**Comment by xinntao** [comment]
@GOZARCK 
There was a bug in --upscale_factor. Now, it is fixed. You can try it again. Thanks~
