### ISSUE TITLE
'NoneType' object has no attribute 'load_state_dict'

### ISSUE THREAD

**Issue by pratikgujral** [TencentARC/GFPGAN#108]
Hi, 

I am running the code "as is" on Google Colab (GPU runtime). Upon executing the following line in the code
`!python inference_gfpgan.py --upscale 2 --test_path inputs/upload --save_root results --model_path experiments/pretrained_models/GFPGANCleanv1-NoCE-C2.pth --bg_upsampler realesrgan`,  I am getting the following error:

```
Traceback (most recent call last):
  File "inference_gfpgan.py", line 113, in <module>
    main()
  File "inference_gfpgan.py", line 56, in main
    half=True)  # need to set False in CPU mode
  File "/usr/local/lib/python3.7/dist-packages/realesrgan/utils.py", line 49, in __init__
    model.load_state_dict(loadnet[keyname], strict=True)
AttributeError: 'NoneType' object has no attribute 'load_state_dict'

```
![image](https://user-images.githubusercontent.com/5672819/145715272-3abb7501-40c4-45bc-b6fe-02fc2c6b757e.png)

It looks like the external code for ESR GAN has changed.

How do I get around this error?

**Comment by xinntao** [comment]
Thanks for reporting this issue. I have fixed it now. Please have a try:-)

**Comment by bolshoytoster** [comment]
The error comes from [this](https://github.com/xinntao/Real-ESRGAN/commit/696e1a6741c912db9d566a162cada43763e57756#diff-a4474ebb6553620e9c0dfec1fcf036d252f2fc68786b59db12296dea144392b0) commit in the [realesrgan](https://github.com/xinntao/Real-ESRGAN) repository, where it no longer handles for model being `None`. This issue should be resolved if we provide a none null model to the `RealESRGANer` class.

**Comment by bochkarev-artem** [comment]
fast response, thank you!
