### ISSUE TITLE
Missing the Code of Conduct

### ISSUE THREAD

**Issue by FahimFBA** [TencentARC/GFPGAN#110]
Hello, while checking your project, I came to realize that it doesn't have any Code of Conduct. Have you considered adding one? If you want to add, then I can submit a PR including that.

**Comment by BluEyedTree** [comment]
It's pretty clear that they don't care. I imagine this code will eventually be used as part of the massive surveillance in China, and the fragmented one here in the states. I can't imagine people are helping to build this completely unethical technology.

**Comment by KarlKemp** [comment]
(1) All contributors must adhere to our ethics policy. 

(1.1) Specifically, they are required not to consider that they may be helping us or the government we closely cooperate with in the great task of using facial recognition to weed out even the last [Uyghurs](https://en.wikipedia.org/wiki/Uyghur_genocide) for forced sterilization, "re-education", or simple disappearance.

(2) All source code is to use three [3] spaces for indentation.

**Comment by xinntao** [comment]
The CODE_OF_CONDUCT.md has been added. 
https://github.com/TencentARC/GFPGAN/blob/master/CODE_OF_CONDUCT.md
