### ISSUE TITLE
重新训练自己的数据集

### ISSUE THREAD

**Issue by JiaweiShiCV** [TencentARC/GFPGAN#12]
您好，请问如果我想训练自己的数据集，是否只需要修改数据集的面部landmarks？
还有另一个问题：在其他条件不变的情况下，训练时增加gpu数量至8，学习率是否需要相应的调整呢？

**Comment by JiaweiShiCV** [comment]
抱歉还有一个问题，您在训练ffhq（512分辨率）时，四卡的训练时长大约是多久

**Comment by xinntao** [comment]
1. 是的， 数据集只需要修改landmarks
2. 八卡训练， 最优的lr应该需要有调整。 但目前这个lr应该可以使用
3. 训练时间： V100 大概5-6days
