### ISSUE TITLE
How to colorize the whole image?

### ISSUE THREAD

**Issue by nrszysiak** [TencentARC/GFPGAN#140]
Hello,

I'm using PaperModel and wondering whether there is an option to colorize the whole image instead of just cropped faces that were restored and put back to the image? Thanks in advance!

**Comment by xinntao** [comment]
Hi，
Sorry that the current model cannot support colorizing the full image~

**Comment by nrszysiak** [comment]
Hi,

No problem - thanks a lot for the prompt reply. Closing this issue.
