### ISSUE TITLE
landmark

### ISSUE THREAD

**Issue by ZZFanya-DWR** [TencentARC/GFPGAN#16]
请问下，预训练里面的landmark里面的眼睛，嘴巴的三个坐标分别代表什么，我想在自己训练集上训练，所以要重新生成这个landmark，谢谢

**Comment by zhangyunming** [comment]
不是只是嘴巴的预训练模型pth吗，在线检测 自己训练数据 不就可以了吗  ， 还需要重新搞吗？可能我理解错了。

**Comment by xinntao** [comment]
@ZZFanya-DWR 
Provide the scripts for extracting landmarks from FFHQ datasets in https://github.com/TencentARC/GFPGAN/blob/master/scripts/parse_landmark.py

You may need to modify it for your own dataset. 
For landmark detection, you may use facexlib (https://github.com/xinntao/facexlib)
