### ISSUE TITLE
Pre-trained models?

### ISSUE THREAD

**Issue by chuanli11** [TencentARC/GFPGAN#2]
Hey, wonder if there is any plan for sharing the pretrained models?

**Comment by BounharAbdelaziz** [comment]
Same question please.
Many thanks in advance !

**Comment by woctezuma** [comment]
I am also eager to test the model with pre-trained models.

Meanwhile, I use [`**GPEN**`](https://github.com/yangxy/GPEN) which, from a quick look, may be a similar approach with great results.

**Comment by xinntao** [comment]
@chuanli11 @BounharAbdelaziz 
The pre-trained models have been updated.

The colab demo: https://colab.research.google.com/drive/1sVsoBd9AjckIXThgtZhGrHRfFI6UUYOo

@woctezuma GFPGAN and GPEN share similar ideas.  You can try the colab demo to see the results.  Thanks~

**Comment by woctezuma** [comment]
Super! Thank you! 👀

**Comment by chuanli11** [comment]
Awesome! Thank you!

**Comment by AK391** [comment]
@xinntao can inference be done on cpu in colab?
