### ISSUE TITLE
Not accepting weights despite being in the right folder

### ISSUE THREAD

**Issue by ABI-projects** [TencentARC/GFPGAN#208]
UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  f"The parameter '{pretrained_param}' is deprecated since 0.13 and will be removed in 0.15, "

Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)

**Comment by elen07zz** [comment]
pip install torchvision==0.12

**Comment by xalteropsx** [comment]
> pip install torchvision==0.12

is this not added ? or repo left forever?
