### ISSUE TITLE
Discriminators loading

### ISSUE THREAD

**Issue by mm-photoaid** [TencentARC/GFPGAN#219]
Hi, I was going through your repo and was interested in reusing your trained discriminators.
Unfortunately I couldnt find how can I load them. I found in `gfpganv1_arch.py` class `FacialComponentDiscriminator`, is this the `torch.nn.Module` that is compatible with weights from`GFPGANv1_net_d.pth` ? I want to load your discriminator to my custom pytorch module, is it even possible to do?

**Comment by hfutxyh** [comment]
Hello, I wanted to ask if you have solved this problem? I also want to use the pretrained discriminator model included in it.
