### ISSUE TITLE
你好大佬，请教几个环境问题

### ISSUE THREAD

**Issue by theoldsong** [TencentARC/GFPGAN#22]
大佬好，今天尝试运行这个项目，安装环境失败。
第一次尝试torch==1.9.0+cu111，提示CUDA driver initialization failed, you might not have a CUDA gpu
第二次尝试torch==1.7.0+cu10.2，提示The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.
之前运行DFDNET和GPEN都是没问题的，请问我这是哪里出问题了？希望百忙之中能抽时间帮忙解答下，感谢！

**Comment by xinntao** [comment]
这是安装pytorch出错了？

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: theoldsong ***@***.***>
Sent: Saturday, July 17, 2021 10:09:25 PM
To: TencentARC/GFPGAN ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TencentARC/GFPGAN] 你好大佬，请教几个环境问题 (#22)


大佬好，今天尝试运行这个项目，安装环境失败。
第一次尝试torch==1.9.0+cu111，提示CUDA driver initialization failed, you might not have a CUDA gpu
第二次尝试torch==1.7.0+cu10.2，提示The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.
之前运行DFDNET和GPEN都是没问题的，请问我这是哪里出问题了？希望百忙之中能抽时间帮忙解答下，感谢！

―

**Comment by theoldsong** [comment]
不是，环境安装没报错，执行python inference_gfpgan_full.py --model_path experiments/pretrained_models/GFPGANv1.pth --test_path inputs/whole_imgs 后报错的

**Comment by xinntao** [comment]
你是安装basicsr使用BASICSR_EXT=True吗？

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by theoldsong** [comment]
是的，按照操作说明的步骤来的
BASICSR_EXT=True pip install basicsr

**Comment by xinntao** [comment]
可能是这个步骤有错误，你可以这样
1.先uninstall
2.安装不要用BASICSR_EXT=True
3.运行命令使用BASICSR_JIT

你先试试这个

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by theoldsong** [comment]
pip uninstall basicsr
BASICSR_JIT=True pip install basicsr
是这个步骤吗？

**Comment by xinntao** [comment]
直接这个pip install basicsr ，BASICSR_JIT=True是在运行的命令里面加，不是在安装命令里面

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by theoldsong** [comment]
好的，我试试，感谢大佬！
