### ISSUE TITLE
How to use GPU

### ISSUE THREAD

**Issue by DrBlou** [TencentARC/GFPGAN#229]
Hi all,

First, its a very nice tool, you did a very good job here !

Sadly, i cant use my RTX3080 GPU to process the images, only the CPU is used, can someone help me with this ?

I can tell my GPU isn't used because of this error : 

UserWarning: The unoptimized RealESRGAN is slow on CPU. We do not use it. If you really want to use it, please modify the corresponding codes.

Can someone tell me how to set GFPGAN so it use my GPU ? 

Thanks a lot in advance

- [ ] 
![image](https://user-images.githubusercontent.com/92190077/182247941-f3fa944d-66fc-49c6-830a-5e468a8421e9.png)

**Comment by elen07zz** [comment]
You need to install nvidia cuda and then install torch with cuda 
conda remove torchvision torchaudio pytorch 
conda install pytorch torchvision torchaudio cudatoolkit=11.6 -c pytorch -c conda-forge

**Comment by DrBlou** [comment]
Thanks a lot it works now !!

**Comment by slymeasy** [comment]
> conda install pytorch torchvision torchaudio cudatoolkit=11.6 -c pytorch -c conda-forge

For me this hands on "solving the environment"

**Comment by lzhchina** [comment]
if args.bg_upsampler == 'realesrgan':
        if not torch.cuda.is_available():  # CPU
            import warnings
            warnings.warn('The unoptimized RealESRGAN is slow on CPU. We do not use it. '
                          'If you really want to use it, please modify the corresponding codes.')
            bg_upsampler = None
