### ISSUE TITLE
处理后的整个照片    颜色发棕 , 和原图片的色调不一样 !!

### ISSUE THREAD

**Issue by lzhmhznr** [TencentARC/GFPGAN#24]
处理后的整个照片    颜色发棕 , 和原图片的色调不一样 !!
![证件照-女](https://user-images.githubusercontent.com/28084126/126767227-09bcafce-0b24-47b4-aaa3-1cbb17eac639.jpg)

**Comment by xinntao** [comment]
@lzhmhznr 目前这个版本，是会更改颜色的。因为再其他数据集上训练，所以可能会有差异。 后面我们会逐渐更新不修改颜色~

**Comment by Tengfei000** [comment]
@xinntao 色调的改变是由于哪一部分的约束导致的？是identity loss吗？ 还是其他？
