### ISSUE TITLE
HI!! Testset!!

### ISSUE THREAD

**Issue by scj0709** [TencentARC/GFPGAN#242]
Hello!!
I am very impressed your paper.
So i want to test it, but when I split it into celeba-hq test set, there are 2824 sheets.
In your paper, it is 3000, can you tell me exactly how you divided it?
Tanks!!

**Comment by huilicici** [comment]
I have the same problem. Only obtain 2824 test images.

**Comment by xinntao** [comment]
We have updated all the testset in https://xinntao.github.io/projects/gfpgan

Please check it~
