### ISSUE TITLE
Permission Denied when Installing setup.py

### ISSUE THREAD

**Issue by Dartterious** [TencentARC/GFPGAN#243]
I have zero code knowledge but can follow instructions well enough. But I've run into the following error and don't know how to fix it. Please help!
![image](https://user-images.githubusercontent.com/109719059/186980241-db0f20b0-fca9-4d06-9985-82368a526a14.png)

**Comment by senhan07** [comment]
Run anaconda with administrator

**Comment by Dartterious** [comment]
Appreciate the reply. I forgot this was open. It has since been resolved some time ago.
