### ISSUE TITLE
error: (-215:Assertion failed) !buf.empty() in function 'imdecode_'

### ISSUE THREAD

**Issue by dongfengxijian** [TencentARC/GFPGAN#245]
First I met the error as follow：
![微信图片_20220829224154](https://user-images.githubusercontent.com/24863806/187227959-c08fef3e-b593-4288-852e-6c7da217db37.png)
Then I add int at ’quality‘ as [https://github.com/TencentARC/GFPGAN/issues/93](url)
But I got another error as follow:
![微信图片_20220829224459](https://user-images.githubusercontent.com/24863806/187228637-672a723a-1745-4a5f-be9a-a69815963282.jpg)

**Comment by juanluisrosaramos** [comment]
This is an opencv problem. I downgrade to another version and it trains without problem.
In my case for example i randomly choose pip install opencv-contrib-python==4.1.0.25
