### ISSUE TITLE
sampling from latent space 

### ISSUE THREAD

**Issue by vlordier** [TencentARC/GFPGAN#250]
could you point to the part of the code where we could :
1- add a parameter to control the amount of reconstruction 
2- sampling from latent space to generate several renders and pick the 'best' reconstruction

**Comment by K780420** [comment]
Why do I have to learn this so precisely?

**Comment by vlordier** [comment]
totally fair :) apologies !

**Comment by K780420** [comment]
I am sorry, I am not sure
I am not able to do it.
It"s hard..
