### ISSUE TITLE
Problem with output.

### ISSUE THREAD

**Issue by Aspector1** [TencentARC/GFPGAN#252]
Good evening! When I use gfpgan, in the restored_imgs folder it gives me a cropped face and everything else is black. What should I do?

I'm using GFPGAN 1.3

It's look like this:
![10045](https://user-images.githubusercontent.com/84536195/188515401-49efd2b6-d806-4227-b0c3-4b9ee3c6e804.png)

**Comment by differentprogramming** [comment]
same

**Comment by differentprogramming** [comment]
Fixed it.

Change:

**Comment by differentprogramming** [comment]
Fixed it

Change:

            bg_upsampler = RealESRGANer(
                scale=2,
                model_path='https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.1/RealESRGAN_x2plus.pth',
                model=model,
                tile=args.bg_tile,
                tile_pad=10,
                pre_pad=0,
                half=True)  # need to set False in CPU mode
                
to:
                            bg_upsampler = RealESRGANer(
                scale=2,
                model_path='https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.1/RealESRGAN_x2plus.pth',
                model=model,
                tile=args.bg_tile,
                tile_pad=10,
                pre_pad=0,
                half=False)  # need to set False in CPU mode

**Comment by Aspector1** [comment]
> Fixed it
> 
> Change:
> 
> ```
>         bg_upsampler = RealESRGANer(
>             scale=2,
>             model_path='https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.1/RealESRGAN_x2plus.pth',
>             model=model,
>             tile=args.bg_tile,
>             tile_pad=10,
>             pre_pad=0,
>             half=True)  # need to set False in CPU mode
> ```
> 
> to: bg_upsampler = RealESRGANer( scale=2, model_path='https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.1/RealESRGAN_x2plus.pth', model=model, tile=args.bg_tile, tile_pad=10, pre_pad=0, half=False) # need to set False in CPU mode

Oh, thank you so much!

**Comment by differentprogramming** [comment]
The point of it is that some gpus don't support half precision numbers.
My 1660 ti being one of them.
