### ISSUE TITLE
Pretty obvious margins after pasting the face back to background. How to solve this?

### ISSUE THREAD

**Issue by lclkent** [TencentARC/GFPGAN#259]
The output pic has a pretty obvious box margin around face regine. I guess it is because the face and backgound was enhanced by different model. Is there a way to handle this? Very much thanks.

**Comment by wangping886** [comment]
same problem .maybe different model cause the pixels  and color are different

**Comment by CodeZeno** [comment]
Same problem for me, I am using a scale of 1 to keep the same image size and just do the face enhance and it is obvious where it has been pasted over the image.
Using GFPGANv1.3.pth and GFPGANCleanv1-NoCE-C2.pth
Using command: python inference_gfpgan.py -i 512x512.png -o /enhanced -v 1.3 --suffix enhanced --bg_upsampler none -s 1 --bg_tile 512
Using command: python inference_gfpgan.py -i 512x512.png -o /enhanced -v 1.2 --suffix enhanced --bg_upsampler none -s 1 --bg_tile 512
Both have this issue. Any way to limit this issue?

**Comment by lclkent** [comment]
Hey guys, I found this phenomenon occasionally happens, and I am pretty sure it is caused by different models. I suppose one way of fixing this is to manually add interpolation around margins or add some kind of blur.

**Comment by K780420** [comment]
![image](https://user-images.githubusercontent.com/97131332/190504531-7719167a-78d0-488a-8138-34199eb4a7cf.jpeg)

**Comment by xinntao** [comment]
> Hey guys, I found this phenomenon occasionally happens, and I am pretty sure it is caused by different models. I also tried to do an extra enhancement on the whole image with background enhance, but the margin still appears. I suppose one way of fixing this is to manually add interpolation around margins or add some kind of blur.

The model itself may introduce some color changes around the face.

This may be a solution.
