### ISSUE TITLE
Love it, thank you! Settings...

### ISSUE THREAD

**Issue by Dariusz1989** [TencentARC/GFPGAN#26]
Hey

I'ts incredible. I was able to restore some old family photos and it's just... incredible! Thank you so much!

However... is it possible to change few params to edit the output?
Size - it's limited to 512, is there a way to do higher?
Auto-cropping - is there a way to disable it somehow? It crops/rotates the head... just wondering if I can control it somehow?

I tried editing > inference_gfpgan_full but nothing good came out of it :D

In any case, thank you amazing for this amazing tool!

**Comment by woctezuma** [comment]
> I'ts incredible. I was able to restore some old family photos and it's just... incredible! Thank you so much!

On a side-note, there are other interesting tools for this purpose. I know about these two:
- https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life
- https://github.com/jantic/DeOldify

**Comment by xinntao** [comment]
@Dariusz1989 Thanks~ It has some limitations now; we will improve it later. But it may take some time （I will improve it in my spare time）. You may take @woctezuma 's suggestion for a temporary solution.

@woctezuma Thanks~

**Comment by xinntao** [comment]
@Dariusz1989 
We have updated it. 
1. support better  putting faces back to original images.
2. Using [Real-ESRGAN](https://github.com/xinntao/Real-ESRGAN) for enhancing background.

You may have a try. 

We will also support the color enhancement and scratch removal later~
Thanks. 

If you still have questions, please re-open this issue.
