### ISSUE TITLE
using my own pretrained stylegan2 network

### ISSUE THREAD

**Issue by MDYLL** [TencentARC/GFPGAN#27]
Hello :)
Thank you very much for your repo. I got a lot of beatiful photos. :))))

I try to use my own pretrained stylegan from official repo 
https://github.com/NVlabs/stylegan2

But I cannot understand how I should use pkl-file, that I have.

I convert it to pt-file by
https://github.com/dvschultz/ai/blob/master/Convert_pkl_to_pt.ipynb
and change yml:
decoder_load_path: experiments/pretrained_models/stylegan2-ffhq-config-f.pt
but got error:
KeyError: 'params_ema'

May be I should use another repo for getting correct pth-file for decoder ?

Thank you :)))

**Comment by MDYLL** [comment]
done:

https://github.com/xinntao/BasicSR/blob/master/docs/HOWTOs.md#How-to-train-StyleGAN2

1. dataset should contain 70K images
2. change yml:
# network structures
network_g:
channel_multiplier:1

network_g:
channel_multiplier:1

you will get pth file for GFPGAN

**Comment by yx-chan131** [comment]
Hi, @MDYLL , so you train a new StyleGAN2 model using BasicSR library? 
May I know how long is the duration for training?

**Comment by MDYLL** [comment]
I think it depends on GPU. In my case it took 3 days. And after I could inference GFPGAN on CPU

**Comment by yx-chan131** [comment]
@MDYLL Thanks for your reply. May I know whether you turn off the generator regularization when training styleGAN2? Because I found that this is the problem that cause my training speed to be extremely slow.

**Comment by MDYLL** [comment]
:)
Nope. Train parameters have been set by default
