### ISSUE TITLE
results are strange while testing on whole img

### ISSUE THREAD

**Issue by tachikoma777** [TencentARC/GFPGAN#29]
Hi, I'm using pretrain model for testing, while testing on align cropped faces, the results are promising. 
However, while testing as whole img the results are wrong, seems the detection is not working well because in results cmp folder there is no faces or sereval faces in one img.

I didn't change the code, is there anything wrong the whole img testing? Thanks in advance.

**Comment by xinntao** [comment]
1. If no face is detected, it will restore it. 
2. As the current model also enhances colors, when putting faces back to the whole image, the results are not good. We will release a model w/o changing colors.

**Comment by tachikoma777** [comment]
> 1. If no face is detected, it will restore it.
> 2. As the current model also enhances colors, when putting faces back to the whole image, the results are not good. We will release a model w/o changing colors.

But I use default test img in original project, it will be strange if no face is detected. results are as follows:
![image](https://user-images.githubusercontent.com/6949661/128117648-e9e62199-995f-4edc-a8c4-499fb3ef511f.png)

**Comment by tachikoma777** [comment]
By the way, I have i small question about the Channel-Split SFT, which is how the F_prior is splited in chanels? How many channel F_prior have? Thanks!

**Comment by xinntao** [comment]
> > 1. If no face is detected, it will restore it.
> > 2. As the current model also enhances colors, when putting faces back to the whole image, the results are not good. We will release a model w/o changing colors.
> 
> But I use default test img in original project, it will be strange if no face is detected. results are as follows:
> ![image](https://user-images.githubusercontent.com/6949661/128117648-e9e62199-995f-4edc-a8c4-499fb3ef511f.png)

Did you use the colab demo? 
It seems that there must be something wrong with face detection.~

**Comment by xinntao** [comment]
> By the way, I have i small question about the Channel-Split SFT, which is how the F_prior is splited in chanels? How many channel F_prior have? Thanks!

Half the original channels~

**Comment by tachikoma777** [comment]
> > > 1. If no face is detected, it will restore it.
> > > 2. As the current model also enhances colors, when putting faces back to the whole image, the results are not good. We will release a model w/o changing colors.
> > 
> > 
> > But I use default test img in original project, it will be strange if no face is detected. results are as follows:
> > ![image](https://user-images.githubusercontent.com/6949661/128117648-e9e62199-995f-4edc-a8c4-499fb3ef511f.png)
> 
> Did you use the colab demo?
> It seems that there must be something wrong with face detection.~

No, I tested on local side. After I recheck the crop region and found that for every input the detection region is always the left up 512*512 block. I tested on both moblienet and resnet detection model.

**Comment by xinntao** [comment]
I have updated the model without colorization. Colab demo: https://colab.research.google.com/drive/1sVsoBd9AjckIXThgtZhGrHRfFI6UUYOo

For your problem, I have not encountered this issue on my side.
