### ISSUE TITLE
want to whole image in the result (without cropping)

### ISSUE THREAD

**Issue by Harighs** [TencentARC/GFPGAN#30]
Is it possible to have whole images as result?
when inference my images are been cropped in the result folder.
I NEED FULL IMAGE AS RESULT

I used "Load extensions just-in-time(JIT)":
`BASICSR_JIT=True python inference_gfpgan_full.py --model_path experiments/pretrained_models/GFPGANv1.pth --test_path inputs/whole_imgs`

**Comment by xinntao** [comment]
1. You can add `--paste-back` option for obtaining the whole image.
2. But the current model will also change colors. So putting back will result in inconsistent results. We will release an improved model later~

**Comment by xinntao** [comment]
I have updated the model, which can generate a reasonable whole image. Colab demo: https://colab.research.google.com/drive/1sVsoBd9AjckIXThgtZhGrHRfFI6UUYOo
