### ISSUE TITLE
[Question] How do I make GFPGAN colorize images on huggingface?

### ISSUE THREAD

**Issue by nixtoshi** [TencentARC/GFPGAN#323]
I've noticed that I don't get colorization on the main sites to demo GFPGAN, is there a way to enable this from https://huggingface.co/spaces/Xintao/GFPGAN ?

Or how would I go about doing this, I'm guessing I'd have to run it in my own server with certain settings or on google colab with custom settings because by default I'm not getting colorization or having that option.

Tried all the versions and the RestoreFormer with these 2 images black and white images:

https://cdn.discordapp.com/attachments/472083679104073738/1064165133502394369/night_vision_example_black_and_white.jpg
https://cdn.discordapp.com/attachments/472083679104073738/1064165133284278422/night_vision_example_black_and_white_copy.jpg

**Comment by AlionSSS** [comment]
- Like this?
![ava_00](https://github.com/TencentARC/GFPGAN/assets/20226368/fe474952-f248-4797-bf5a-b70d3e85dcce)
- There is a solution. https://github.com/TencentARC/GFPGAN/issues/201#issuecomment-1703679814

**Comment by nixtoshi** [comment]
Thanks for the reply! I used DeepAI for this: https://deepai.org/machine-learning-model/colorizer

![colorized spaceman deepai org](https://github.com/TencentARC/GFPGAN/assets/6463592/691eafde-042a-4ed2-bea1-30d2fa9ca8d7)
