### ISSUE TITLE
How do I force it to work on the CPU? 

### ISSUE THREAD

**Issue by joe-eis** [TencentARC/GFPGAN#328]
How do I force it to work on the CPU? 
My GPU RAM is too small with 2GB, I get the message

` "RuntimeError: CUDA out of memory. Tried to allocate 154.00 MiB (GPU 0; 1.96 GiB total capacity; 927.97 MiB already allocated; 72.44 MiB free; 1.05 GiB reserved in total by PyTorch)"`

**Comment by medalawi** [comment]
try this or lower value to 128

Windows: set 'PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512'

Linux: export 'PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512'

**Comment by joe-eis** [comment]
Unfortunately no. Change the allocation
export 'PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512'
in the SHELL bevor  I execute the command: " inference_gfpgan.py"

brings only minor change:
RuntimeError: CUDA out of memory. Tried to allocate 154.00 MiB (GPU 0; 1.96 GiB total capacity; 775.63 MiB already allocated; 99.88 MiB free; 920.00 MiB reserved in total by PyTorch)

also the line 
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = max_split_size_mb:512>'

in the script does not change anything

**Comment by medalawi** [comment]
you have too low VRam  --  4GB is the minimum but try to downgrade torch version  to 1.7

**Comment by joe-eis** [comment]
Thank you for this useful information.

Unfortunately, my notebook has a 2 GB Nvidia installed.
The program can work on the CPU even if I would not use an Nvidia. But it recognizes the CUDA capable card even if it has too little memory.

**Comment by medalawi** [comment]
find this line and remove "not" after if statment   to force using CPU
 
  if not torch.cuda.is_available():  #cpu

**Comment by medalawi** [comment]
i found this line in gfpgan/utils.py   and  /GFPGAN/inference_gfpgan.py

**Comment by joe-eis** [comment]
Thank you, the idea to remove 'not' is great and brought the solution.

**Comment by lzhchina** [comment]
if args.bg_upsampler == 'realesrgan':
        if not torch.cuda.is_available():  # CPU
            import warnings
            warnings.warn('The unoptimized RealESRGAN is slow on CPU. We do not use it. '
                          'If you really want to use it, please modify the corresponding codes.')
            bg_upsampler = None
