### ISSUE TITLE
please set recompute_scale_factor=True

### ISSUE THREAD

**Issue by joe-eis** [TencentARC/GFPGAN#329]
Because my notebook contains only a 2GB RAM graphics card Nvidia, I switched to the Intel graphics.

The execution of python3 inference_gfpgan.py
I now get the following warning:

`envs/GFPGAN/lib/python3.8/site-packages/torch/nn/functional.py:3502: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True.`

Where can I handle this message?
The string " recompute_scale_factor" is too often in this file functional.py ...

**Comment by Sujit7632** [comment]
![Uploading 3DLUTmobile_20230207_150328.jpeg…]()

**Comment by Sujit7632** [comment]
3

**Comment by Sujit7632** [comment]
1.

**Comment by Sujit7632** [comment]
- [ ]

**Comment by Sujit7632** [comment]
4

**Comment by Sujit7632** [comment]
5
