### ISSUE TITLE
FaceRestoreHelper 

### ISSUE THREAD

**Issue by Roenbaeck** [TencentARC/GFPGAN#35]
I get the following error with the latest version: 
```
Traceback (most recent call last):
  File "inference_gfpgan_full.py", line 132, in <module>
    face_helper = FaceRestoreHelper(
TypeError: __init__() got an unexpected keyword argument 'device'
```
Removing the `device` parameter in the call to `FaceRestoreHelper` solved my problem. The call in inference_gfpgan_full.py then becomes: 
```
    # initialize face helper
    face_helper = FaceRestoreHelper(
        args.upscale_factor,
        face_size=512,
        crop_ratio=(1, 1),
        det_model='retinaface_resnet50',
        save_ext='png')
```

**Comment by woctezuma** [comment]
The bug was introduced in this commit: https://github.com/TencentARC/GFPGAN/commit/7f67e12999de9282bc14de4d3afeee138106b6f5

**Comment by xinntao** [comment]
you need to update the facexlib version to 0.2.0.1

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Lars Rönnbäck ***@***.***>
Sent: Saturday, August 7, 2021 2:10:44 AM
To: TencentARC/GFPGAN ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TencentARC/GFPGAN] FaceRestoreHelper (#35)


I get the following error with the latest version:

Traceback (most recent call last):
  File "inference_gfpgan_full.py", line 132, in <module>
    face_helper = FaceRestoreHelper(
TypeError: __init__() got an unexpected keyword argument 'device'


Removing the device parameter in the call to FaceRestoreHelper solved my problem. The call in inference_gfpgan_full.py then becomes:

    # initialize face helper
    face_helper = FaceRestoreHelper(
        args.upscale_factor,
        face_size=512,
        crop_ratio=(1, 1),
        det_model='retinaface_resnet50',
        save_ext='png')
