### ISSUE TITLE
channel_multiplier

### ISSUE THREAD

**Issue by JiaweiShiCV** [TencentARC/GFPGAN#38]
您好， @xinntao 
我注意到新的Clean版本，你将`channel_multiplier`从1调整为2。
但当我查看`train_gfpgan_v1_simple.yml`时发现预训练的stylegan2模型没有作相应改变：`StyleGAN2_512_Cmul1_FFHQ_B12G4_scratch_800k.pth`，请问这是和原来`channel_multiplier=1`时一模一样的stylegan2模型吗？

**Comment by xinntao** [comment]
Clean结构是不同的stylegan2 模型

**Comment by JiaweiShiCV** [comment]
不好意思我看错了，`train_gfpgan_v1_simple.yml`是去颜色抖动、去鉴别器的option，我以为是clean版本的option了。
1、请问可以公开clean版本的gfpgan训练option吗？
2、
```
if arch == 'clean':
    self.gfpgan = GFPGANv1Clean(
        out_size=512,
        num_style_feat=512,
        channel_multiplier=channel_multiplier,
        decoder_load_path=None,
        fix_decoder=False,
        num_mlp=8,
        input_is_latent=True,
        different_w=True,
        narrow=1,
        sft_half=True)
```
我注意到`fix_decoder=False`，您训练clean版本的gfpgan时放开了stylegan生成器的权重迭代是吗？
