### ISSUE TITLE
Why is the effect of processing photos locally not as good as online?

### ISSUE THREAD

**Issue by hktalent** [TencentARC/GFPGAN#391]
Why is the effect of processing photos locally not as good as online?
<img width="559" alt="image" src="https://github.com/TencentARC/GFPGAN/assets/18223385/689dea45-74f8-4cb2-ac7c-c04ae66eae44">
online:
https://replicate.com/xinntao/gfpgan/
<img width="257" alt="image" src="https://github.com/TencentARC/GFPGAN/assets/18223385/1e3248b1-2dac-4ad7-b837-9477300fced9">

why?

**Comment by RamiSJ12** [comment]
This is because of the photo pixels.

**Comment by RamiSJ12** [comment]
The online web app has complete set of coding in the framework and libraries where it has codes can adjust the image resolution, while the locally edition of software will do some adjustments to be compatible with your OS.

**Comment by hktalent** [comment]
@RamiSJ12 Thank you very much for your enthusiastic reply

What do you mean is that my Macos Intel CPU performs well, even with the same code

Is there a difference within the normal range?

**Comment by RamiSJ12** [comment]
Core i9-12900HK is the one that comes close to matching the general performance of the M1 Max chip.

So the range is between M1 & M2.

However, if you are using Mac OS then I suggest you get the software from Apple Store for Graphics Designing or image editing, or AI integrations, as those are more advance.

**Comment by RamiSJ12** [comment]
@hktalent 

https://www.libhunt.com/r/GFPGAN

This link has the Alternatives for GFPGAN, please check it.

**Comment by alif99y** [comment]
Please solve my problem, I was using jetta let me use it

**Comment by hktalent** [comment]
@RamiSJ12 Thank you again. I can end this question for you

Perhaps it is really due to hardware limitations that the effect is not ideal



I can only console myself this way for now
