### ISSUE TITLE
Hugging Face Hub Integration

### ISSUE THREAD

**Issue by osanseviero** [TencentARC/GFPGAN#4]
Hi GFPGAN team!

Would you be interested in sharing the pretrained models in the [Hugging Face Hub](https://huggingface.co/)? The Hub offers free hosting of models (over 10,000 models have been uploaded by many research organizations) and it would make your work more accessible and visible to others. 

We could create a widget for anyone to try the model directly in the browser. The only thing required would be to upload the models to the Hub. I'm happy to answer any questions about this.

Happy to hear your thoughts,
Omar

**Comment by xinntao** [comment]
@osanseviero Thanks!
We would like to share the pretraiend models. 

Is there any instruction?

**Comment by osanseviero** [comment]
Hi there!

I think ideally you would set up an organization so all your models are easily found in the Hub.

The repos in the Hub are git-based, so if you're used to GitHub processes, it should be very similar. We have a video about this in our documentation - https://huggingface.co/docs/main#how-can-i-loadpush-fromto-the-hub. That same page has a other information that might be useful.

If you agree, we can set up a shared Slack channel so we can discuss more efficiently 😄 

FYI @LysandreJik

**Comment by xinntao** [comment]
@osanseviero  @LysandreJik
Hi， sorry for the delay~

1. Thanks for your advice, we are glad to create an organization in Hugging Face Hub.
2. This link https://huggingface.co/docs/main#how-can-i-loadpush-fromto-the-hub seems invalid. Could you please help to check it?
3. I agree to set up a shared Slack channel. 
Wait for your reply~ Thanks!

**Comment by osanseviero** [comment]
Hi @xinntao!

We now have a full guide on how to push a model to the Hub. I hope you find it useful! https://huggingface.co/docs/hub/adding-a-model.

About Slack, feel free to share your email (you can send your email to omar at huggingface.co if you prefer). I'll then send you a message in Slack.
