### ISSUE TITLE
pip install  gfpgan==1.3.8 error 

### ISSUE THREAD

**Issue by lix19937** [TencentARC/GFPGAN#403]
Could not find a version that satisfies the requirement tb-nightly (from gfpgan) 

INFO: pip is looking at multiple versions of gfpgan to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement tb-nightly (from gfpgan) (from versions: none)
ERROR: No matching distribution found for tb-nightly

**Comment by lix19937** [comment]
Has sloved, closed !

**Comment by before31** [comment]
How did you slove it? i meet the same problem.

**Comment by ganapathiarika456** [comment]
Hi

**Comment by before31** [comment]
> @before31 You should be `pip install tb-nightly ` first.

thanks. i changed the mirror from douban to baidu, then installed successfully.

`pip install gfpgan==1.3.8 -i https://mirror.baidu.com/pypi/simple`
