### ISSUE TITLE
About the rgb results from from Degradation Removal.

### ISSUE THREAD

**Issue by NNNNAI** [TencentARC/GFPGAN#42]
Thanks for sharing your wonderful work!!!!!!
I have try to visualize the rgb restoration result (512*512) for the degradation removal module by using the the code below.
```
    _, output_list = gfpgan(cropped_face_t, return_rgb=True)
    output = output_list[-1]
    # convert to image
    rec_face = tensor2img(output.squeeze(0), rgb2bgr=True, min_max=(-1, 1))
```
But I got such a results, the color of the restoration result from degradation removal module is different from the original image, is this normal? Many thanks~, have a nice day.
![image](https://user-images.githubusercontent.com/30747212/129481306-021d7c76-447e-4357-905c-e6d858ee3c45.png)

**Comment by xinntao** [comment]
Hi @NNNNAI 

As we do not force the output of the degradation model to be a normal image. So, this phenomenon is normal.
