### ISSUE TITLE
only paste back from already restored faces

### ISSUE THREAD

**Issue by NoUserNameForYou** [TencentARC/GFPGAN#46]
Is it possible to do this without restoring faces again just with 2x esrgan?

like 

"python inference_gfpgan.py --upscale 2 --model_path nomodel --test_path results/restored_faces --save_root results/restored_images --paste_back_only"

?

**Comment by xinntao** [comment]
Did you mean that you want to paste restored face (from other sources) to the images upsampled by real-esrgan?

**Comment by NoUserNameForYou** [comment]
"(from other sources)"

Doesn't matter but also that, yes. 

If I used gfpgan without paste back, I would like to continue with just pasteback without any restoration from beginning.

**Comment by xinntao** [comment]
I think you can modify https://github.com/xinntao/facexlib/blob/master/facexlib/utils/face_restoration_helper.py

An easy way is to change the value face_helper.restored_faces with restored faces from other sources.

**Comment by NoUserNameForYou** [comment]
There's no "face_helper.restored_faces" in the code, I ctrl+f and searched.

**Comment by xinntao** [comment]
Sorry for the misunderstanding. 

I mean in your script, you can re-set the `restored_faces`, for example:

```
...
face_helper = FaceRestoreHelper()

face_helper.read_img()
face_helper.get_face_landmarks_5()
face_helper.align_warp_face()
...
face_helper.restored_faces = #your custom restored faces#
...
face_helper.paste_faces_to_input_image()




```

**Comment by NoUserNameForYou** [comment]
Thank you, will try it later.
