### ISSUE TITLE
Train with GPU and inference without GPU. Is it possible ?

### ISSUE THREAD

**Issue by MDYLL** [TencentARC/GFPGAN#47]
Hello :)
One more - thank you very much for your beatifull project !

1. I trained model on my ouw dataset - mymodel.pth
2. I ran inference on CPU with your model - GFPGANCleanv1-NoCE-C2.pth
3. I see that GFPGANv1.pth (and mymodel.pth) has 2x size that GFPGANCleanv1-NoCE-C2.pth

So, how I can transform mymodel.pth for using inference on CPU ? or may be I should train anotther model ?

Thank you :))

**Comment by xinntao** [comment]
@MDYLL 

1.  GFPGANv1.pth and GFPGANCleanv1-NoCE-C2.pth have two different architectures. So, they could not be transferred to each other currently.
2. As GFPGANv1.pth requires custom CUDA extensions, so it could not be run on CPU.

**Comment by MDYLL** [comment]
Thank you for answer. Could I train GFPGANCleanv1-NoCE-C2.pth on my own dataset (with CUDA) ?

**Comment by xinntao** [comment]
Currently， I have not updated the original architecture for GFPGANCleanv1-NoCE-C2.pth. So you could not finetune GFPGANCleanv1-NoCE-C2.pth. 

I may update it later.

**Comment by MDYLL** [comment]
Ok, thank you :)
and good luck with all your projects ;)
