### ISSUE TITLE
关于数据集的问题

### ISSUE THREAD

**Issue by izhaolinger** [TencentARC/GFPGAN#549]
非常感谢作者的贡献，GFPGAN的效果让人惊艳。我尝试使用私有数据集定制化训练，但train_gfpgan_v1配置文件中所需的数据集格式，我不太理解，请问：

1. train - dataroot_gt参数下是512x512尺寸的高清图片吗？
2. val - dataroot_lq和dataroot_gt参数下应该填写什么路径呢？
3. 如果我想在v1.2模型上做微调，我应该怎么加载预训练模型呢？

感谢，期待回复！

**Comment by doniaa24** [comment]
Training Data Format: Yes, for the train - dataroot_gt parameter, you should use high-definition images with a size of 512x512 pixels.
Validation Data Paths:
val - dataroot_lq: This should be the path to your low-quality or damaged images. These are the images that your model will attempt to restore.
val - dataroot_gt: This path should lead to the clean or undamaged versions of the images specified in dataroot_lq. It is crucial for assessing the model's performance during validation.
Note: Ensure that both directories (dataroot_lq and dataroot_gt) contain the same number of images  as each damaged image in dataroot_lq should have its matching clean version in dataroot_gt for effective training and validation.

**Comment by izhaolinger** [comment]
> Training Data Format: Yes, for the train - dataroot_gt parameter, you should use high-definition images with a size of 512x512 pixels. Validation Data Paths: val - dataroot_lq: This should be the path to your low-quality or damaged images. These are the images that your model will attempt to restore. val - dataroot_gt: This path should lead to the clean or undamaged versions of the images specified in dataroot_lq. It is crucial for assessing the model's performance during validation. Note: Ensure that both directories (dataroot_lq and dataroot_gt) contain the same number of images as each damaged image in dataroot_lq should have its matching clean version in dataroot_gt for effective training and validation.

非常感谢您的回复，很有帮助！

**Comment by Bobchenyx** [comment]
> 非常感谢作者的贡献，GFPGAN的效果让人惊艳。我尝试使用私有数据集定制化训练，但train_gfpgan_v1配置文件中所需的数据集格式，我不太理解，请问：
> 
> 1. train - dataroot_gt参数下是512x512尺寸的高清图片吗？
> 2. val - dataroot_lq和dataroot_gt参数下应该填写什么路径呢？
> 3. 如果我想在v1.2模型上做微调，我应该怎么加载预训练模型呢？
> 
> 感谢，期待回复！

您好, 请问可以加下您联系方式嘛? 想咨询有关模型微调相关的问题
