### ISSUE TITLE
RuntimeError: Could not run 'torchvision::roi_align' with arguments from the 'CUDA' backend. 

### ISSUE THREAD

**Issue by lxy2017** [TencentARC/GFPGAN#6]
When I train the code, I get the following error

RuntimeError: Could not run 'torchvision::roi_align' with arguments from the 'CUDA' backend. 'torchvision::roi_align' is only available for these backends: [CPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].

![image](https://user-images.githubusercontent.com/9693098/122701302-7de87d00-d27f-11eb-8376-77149695cc22.png)

**Comment by xinntao** [comment]
I have not encountered this issue. 
May check the torchvision ? （the version in my env is torchvision             0.8.2）

**Comment by lxy2017** [comment]
> I have not encountered this issue.
> May check the torchvision ? （the version in my env is torchvision 0.8.2）

Thanks!
It works for torchvision 0.8.2
