### ISSUE TITLE
如何降低美颜效果

### ISSUE THREAD

**Issue by jorjiang** [TencentARC/GFPGAN#60]
个人觉得增强后的人脸好像美颜太过了一点 过于平滑 细节不够。请问一下我自己重新训练能否降低美颜效果，应该修改哪里最好呢

**Comment by jorjiang** [comment]
能问一下 你是用什么做的美颜吗 好有个比较

**Comment by CongYuSanXun** [comment]
> 这块目前是依赖效果于数据的。目前的做法是对训练的真实情况进行了美颜等处理。可以弱化这块美颜。

请问可以消除v2模型的锐化效果吗？

**Comment by CongYuSanXun** [comment]
> 这块当前是依赖效果于数据的。目前的做法是对训练的真实情况进行了美颜等处理。可以弱化这块美颜。

请问可以消除v2模型的锐化效果吗？提前谢谢。

**Comment by jorjiang** [comment]
> 这块目前是依赖于数据的。目前的效果是对 训练的ground-truth进行了 美颜等处理。 可以弱化这块美颜。

谢谢 能问下你是用什么做的美颜吗 我自己调的时候有个参照
