### ISSUE TITLE
Pre trained models for transfer learning

### ISSUE THREAD

**Issue by eduardoGo** [TencentARC/GFPGAN#68]
Hello, first, congratulations for this awesome work!!

I'm applying this model to another problem. The ideia is use transfer learning. However, I just found one model (pretrain_network_g) for load.
![image](https://user-images.githubusercontent.com/26190178/133925915-ad7e6227-7e49-4158-ab45-498a4afc7823.png)

Because this, the training start with psnr = ~10. Could the authors provide the another models (pretrain_network_d, pretrain_network_d_left_eye, pretrain_network_d_right_eye, pretrain_network_d_mouth)?

**Comment by xinntao** [comment]
Sorry for the late reply.

You can find those models:

Google Drive： https://drive.google.com/drive/folders/17rLiFzcUMoQuhLnptDsKolegHWwJOnHu?usp=sharing
OR 
Tencent Cloud: https://share.weiyun.com/ShYoCCoc
