### ISSUE TITLE
"GFPGANCleanv1-NoCE-C2.pth" file not downloading for me.

### ISSUE THREAD

**Issue by Jordon87** [TencentARC/GFPGAN#70]
So I've been trying to download a pre-trained model for the AI, but for some odd reason i can't even get it to download properly. Instead, I always get greeted with this error.
![Capture](https://user-images.githubusercontent.com/38020644/134106453-4090d1a9-ddfd-4b02-a33b-8bf17fe010b6.PNG)
I've tried doing some workarounds to get it actually downloading, but no such luck. If anyone could try and help, that would be nice for me.

**Comment by Rongcong28** [comment]
I have the same problem as you :\

**Comment by cravussin** [comment]
Same here, since yesterday.

**Comment by xinntao** [comment]
I can download this file now: https://github.com/TencentARC/GFPGAN/releases/download/v0.2.0/GFPGANCleanv1-NoCE-C2.pth

Can you try again?

**Comment by Jordon87** [comment]
Ah alright it's working now.
