### ISSUE TITLE
重新设置图像的退化过程

### ISSUE THREAD

**Issue by HaolyShiit** [TencentARC/GFPGAN#73]
您好，我想修改人脸图像的退化过程重新训练，从您的代码上看退化过程应该是通过train_gfpgan_v1.yml设置参数，调用basicsr中的函数实现的。但basicsr中具体的调用过程没有看到，能否告知下大致涉及到的函数和退化调用的过程？

**Comment by xinntao** [comment]
涉及到的函数在这里： https://github.com/xinntao/BasicSR/blob/master/basicsr/data/degradations.py
退化调用过程在这里： https://github.com/TencentARC/GFPGAN/blob/f6d3f706466e82afbe091abc033c7a91036f8f9a/gfpgan/data/ffhq_degradation_dataset.py#L146-L192

**Comment by xinntao** [comment]
如果没有其他问题，我先把这个issue close了。若有问题，再开启呐

**Comment by chenloveheimei** [comment]
> random_mixed_kernels

我也遇到这个问题，请问你怎么解决呢

**Comment by chenloveheimei** [comment]
> 感谢解答，我现在又有一个问题，麻烦帮忙看看。
> 
> 我重新尝试了下，发现通过train_gfpgan_v1.yml设置参数可以修改数据的退化过程，但GFPGAN/gfpgan/data/ffhq_degradation_dataset.py似乎并没有被用到，我在ffhq_degradation_dataset.py内添加了断点和打印都没有触发，甚至我删了ffhq_degradation_dataset.py算法还是可以正常训练，这一块还是有点不太清楚，您可以详细讲一下吗？

我也遇到这个问题，请问你怎么解决呢

**Comment by timfu248** [comment]
> 感谢解答，我现在又有一个问题，麻烦帮忙看看。
> 
> 我重新尝试了下，发现通过train_gfpgan_v1.yml设置参数可以修改数据的退化过程，但GFPGAN/gfpgan/data/ffhq_degradation_dataset.py似乎并没有被用到，我在ffhq_degradation_dataset.py内添加了断点和打印都没有触发，甚至我删了ffhq_degradation_dataset.py算法还是可以正常训练，这一块还是有点不太清楚，您可以详细讲一下吗？

pip uninstall gfpgan
pip install -e .
