### ISSUE TITLE
About the facexlib

### ISSUE THREAD

**Issue by wzy0903** [TencentARC/GFPGAN#9]
Thanks for your open source code.
I have install the facexlib according to the requirement document.
But I got this problem.

FileNotFoundError: [Errno 2] No such file or directory: '/home/ziy/anaconda3/envs/python37/lib/python3.7/site-packages/facexlib/weights/tmpseizp2dz'

(python37) ziy@:/home/ziy/GFPGAN$ pip install facexlib
Requirement already satisfied: facexlib in /home/ziy/anaconda3/envs/python37/lib/python3.7/site-packages (0.1.3)
Requirement already satisfied: numpy in /home/ziy/anaconda3/envs/python37/lib/python3.7/site-packages (from facexlib) (1.21.0)

Do you know the reason？ Looking forward to your reply.

**Comment by wzy0903** [comment]
My environment is python3.7.1  pytorch 1.9.0

**Comment by lxy2017** [comment]
step1: build folder weights in /home/ziy/anaconda3/envs/python37/lib/python3.7/site-packages/facexlib/   
step2: run code again
It works for me

**Comment by wzy0903** [comment]
> step1: build folder weights in /home/ziy/anaconda3/envs/python37/lib/python3.7/site-packages/facexlib/
> step2: run code again
> It works for me

sorry，what command is used to build step one.

**Comment by xinntao** [comment]
@wzy0903 
Thanks for reporting this issue. 

I have updated the facexlib package. You could re-install it. It should OK now. 
If you still have questions, please let me know.
