### ISSUE TITLE
NameError: name 'fused_act_ext' is not defined

### ISSUE THREAD

**Issue by alexliyang** [TencentARC/GFPGAN#90]
参考使用了：
BASICSR_EXT=True BASICSR_JIT=True pip install basicsr

后，还是存在这个问题，还有什么办法解决吗

**Comment by alexliyang** [comment]
使用本地编译安装正常了：
CUDA_HOME=/usr/local/cuda \
CUDNN_INCLUDE_DIR=/usr/local/cuda \
CUDNN_LIB_DIR=/usr/local/cuda \
BASICSR_EXT=True python setup.py develop

**Comment by dongfengxijian** [comment]
怎么解决这个问题的？
